Backend tests
Adrian-Tamas/python-behave-automation-quickstart pull request #1
Opened 2019-07-17 08:56 UTC by rarestomos

2019-07-18 07:37 UTC, Adrian-Tamas requested changes

2019-07-18 07:37 UTC, Adrian-Tamas commented on actions/api/reservation_endpoint_actions.py
> +def do_get_reservation_by_book_id_or_user_id(param, param_id):
update parameter names to something more relevant like "entity_name" and "entity_id" or split the method into 2 separate ones for book and user

2019-07-18 07:37 UTC, Adrian-Tamas commented on actions/api/reservation_endpoint_actions.py
> +def do_delete_reservation_by_book_id_or_user_id(param, param_id):
same regarding the method parameters

2019-07-18 07:37 UTC, Adrian-Tamas commented on actions/api/reservation_endpoint_actions.py
> +def do_put_request_to_update_reservation(user_id, book_id, data):
maybe also change in the actions the data parameter to the corresponding entity - book, user, reservation

2019-07-18 07:37 UTC, Adrian-Tamas commented on configuration/dev_configuration.py
> +        self.chromedriver_path = self.configuration[self.ENV_NAME]["chromedriver_path"]
driver path is usually set up as an env var not config var since it's specific for each machine

2019-07-18 07:37 UTC, Adrian-Tamas commented on logging.json
> +        "python-behave-automation-quickstart": {
why change this? create a second value if needed. the original was set for the report portal lib

2019-07-18 07:37 UTC, Adrian-Tamas commented on models/endpoints/books_model.py
> +from collections import namedtuple
no need to have the "endpoints" folder as the models will be exclusive to endpoints. For PageObjects we will have a separate folder

2019-07-18 07:37 UTC, Adrian-Tamas commented on models/endpoints/reservations_model.py
> +fake = Faker()
you are not using faker here so you don't need it. You could use if for dates as it has future_date as an option

2019-07-18 07:37 UTC, Adrian-Tamas commented on models/endpoints/users_model.py
> +fake = Faker()
you could add a custom localization to Faker from the config to be able to test for any supported language, which may be an interesting enhancement

2019-07-18 07:37 UTC, Adrian-Tamas commented on requirements.txt
> +selenium
remove the requirements for the frontend testing and the files

2019-07-18 07:37 UTC, Adrian-Tamas commented on tests/environment.py
> +from selenium import webdriver
remove the frontend stuff

2019-07-18 07:37 UTC, Adrian-Tamas commented on tests/features/backend/book/create_book.feature
> +  Scenario: I can add a new book to the database
Test scenario should be "I can add a new book", you should not care how it is stored as you don't check that

2019-07-18 07:37 UTC, Adrian-Tamas commented on tests/features/backend/book/create_book.feature
> +    Given I have a new book added into database
The same with the step names. "Given already have a book" ... keep it simple

2019-07-18 07:37 UTC, Adrian-Tamas commented on tests/features/backend/book/create_book.feature
> +    Given I have a correct Book configuration
Rename to "Given I have a correct book entity" or "Given I have a correct book payload" and keep this consistent. We do not have configurations here

2019-07-18 07:37 UTC, Adrian-Tamas commented on tests/features/backend/book/create_book.feature
> +    Then I receive an error that the author is required
You could add tests for same author different tiles and same title different authors, with one or more authors

2019-07-18 07:37 UTC, Adrian-Tamas commented on tests/features/backend/book/create_book.feature
> +  Scenario: I cannot add a new book without his title
I cannot add a new book without **its** title,  same below. The gender of the book is not male

2019-07-18 07:37 UTC, Adrian-Tamas commented on tests/features/backend/book/get_books.feature
> +    Then I receive an error that the book was not found
check the new line at the end of files for multiple ones

2019-07-18 07:37 UTC, Adrian-Tamas commented on tests/features/backend/reservation/get_reservations.feature
> +  @mda
unneeded tag

2019-07-18 07:37 UTC, Adrian-Tamas commented on tests/steps/backend/reservation/create_reservation_steps.py
> +    context.user_id = context.response.json()['id']
make a response local variable since you use context.response.json() so many times

2019-07-18 07:37 UTC, Adrian-Tamas commented on tests/steps/backend/reservation/get_reservations_steps.py
> +    assert_that(context.response.status_code).is_equal_to(200)
local variable response instead of context.response.json() everywhere

2019-07-18 08:32 UTC, rarestomos commented on configuration/dev_configuration.py
> +        self.chromedriver_path = self.configuration[self.ENV_NAME]["chromedriver_path"]
Will be removed for now, since the PR is for backend implementation

2019-07-18 08:38 UTC, rarestomos commented on logging.json
> +        "python-behave-automation-quickstart": {
Will be changed as it was before

2019-07-19 10:51 UTC, rarestomos commented on tests/features/backend/book/create_book.feature
> +    Then I receive an error that the author is required
Tests added: [1] same author, different titles, [2] same title, different authors

2019-07-30 07:26 UTC, Adrian-Tamas approved these changes

2019-07-31 07:24 UTC, merged